---
- hosts: localhost
  gather_facts: no
  roles:
    - nkp-checks
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  vars:
    ANSIBLE_HOST_KEY_CHECKING: "False"
    image_url:                                       # url to download image from nutanix portal 
    IMAGE_NAME:                                      # Image name - corresponding to the above url
    SSH_PUBLIC_KEY:                                  # SSH key of the local machine,used by ansible to connect to the test VM
    NUTANIX_ENDPOINT:                                # Prism Central IP address
    NUTANIX_USER: admin                              # Prism Central username
    NUTANIX_PASSWORD: ''                             # Prism Central password
    NUTANIX_PORT: 9440                               # Prism Central port (default: 9440)                                          
    NUTANIX_PRISM_ELEMENT_CLUSTER_NAME:              # Prism Element cluster name - Ex: PHX-POC207
    CONTROL_SUBNET:                                  # controlplane subnet name
    WORKER_SUBNET:                                   # worker subnet name
    NUTANIX_STORAGE_CONTAINER_NAME:                  # Change to your preferred Prism storage container
    DS_IP:                                           # Dataservices IP of the prism element cluster
    airgapped: "false"                               # Change to true if airgapped environment
    #registry:                                       # Private Image registry if airgapped
    #management_cluster: "true"                      # set to true if testing for management cluster
    #workload_cluster_subnets: ""                    # If management_cluster is set to true, then specify the list of workload cluster subnets (cluster1:subnet1,cluster2:subnet2)
    ansible_connection: local
    #ansible_python_interpreter: /root/.local/pipx/venvs/ansible-core/bin/python    # facultative, python_interpreter path if you're using different python interpreter and/or from venv.